language: php

dist: trusty
sudo: required

cache:
  directories:
    - $HOME/.composer/cache/files

php:
  - 7.1
  - 7.2

services:
  - mysql

env:
  - DB=mysql
  - DB=mariadb

install:
  - composer install -n

before_script:
  - sh -c "if [ '$DB' = 'mariadb' ]; then sudo apt-get remove mysql-common mysql-server && sudo service mysql start; fi"

script:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS tests_tmp'
  - ./vendor/bin/phpunit tests
